/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JOptionPane;
import java.sql.SQLException;
/**
 *
 * @author monfo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloLbl = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        habitacionButton = new javax.swing.JButton();
        reservaButton = new javax.swing.JButton();
        pasajeroButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloLbl.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        tituloLbl.setText("SOFTWARE HOTELERO");
        tituloLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sitio-web (3).png"))); // NOI18N

        habitacionButton.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        habitacionButton.setText("Cargar Habitaciones");
        habitacionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habitacionButtonActionPerformed(evt);
            }
        });

        reservaButton.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        reservaButton.setText("Gestión de Reservas");
        reservaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservaButtonActionPerformed(evt);
            }
        });

        pasajeroButton.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        pasajeroButton.setText("Cargar Pasajero");
        pasajeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasajeroButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(reservaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(habitacionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pasajeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tituloLbl))
                .addGap(25, 25, 25)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(tituloLbl)
                .addGap(70, 70, 70)
                .addComponent(pasajeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(habitacionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reservaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pasajeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasajeroButtonActionPerformed
        Pasajero pasajero = new Pasajero();
        pasajero.setLocationRelativeTo(null);
        pasajero.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_pasajeroButtonActionPerformed

    private void habitacionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habitacionButtonActionPerformed
        Habitacion habitacion = new Habitacion();
        habitacion.setLocationRelativeTo(null);
        habitacion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_habitacionButtonActionPerformed

    private void reservaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservaButtonActionPerformed
     try {
        Reserva reserva = new Reserva();  // Intentar crear la reserva
        reserva.setLocationRelativeTo(null);  // Centrar la ventana
        reserva.setVisible(true);  // Mostrar la ventana
        this.setVisible(false);  // Ocultar la ventana actual
    } catch (SQLException ex) {
        // Aquí puedes manejar la excepción, por ejemplo, mostrar un mensaje de error
        JOptionPane.showMessageDialog(this, "Error al crear la reserva: " + ex.getMessage(), 
                                      "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
    }//GEN-LAST:event_reservaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Menu menu = new Menu();
                menu.setLocationRelativeTo(null);
                menu.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton habitacionButton;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JButton pasajeroButton;
    private javax.swing.JButton reservaButton;
    private javax.swing.JLabel tituloLbl;
    // End of variables declaration//GEN-END:variables
}
